version: '3'

services:
    postgres:
        image: 'postgres:latest'
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: 'notelocker'
            POSTGRES_PASSWORD: 'password'

    api:
        build: './api'
        depends_on:
            - 'postgres'
        ports:
            - '3001:3001'

    frontend:
        build: './frontend'
        depends_on:
            - 'api'
        ports:
            - '3000:3000'
